### PR TITLE
Update About Us

### LINKED ISSUE #35: Update AboutUs.md
Add details of developers of Nuudle

### PR DESCRIPTION
**Pull request by WadeForward**
update particulars for Zhang Wanlin:
1. update AboutUs.md
2. add zhangwanlin.md
3. add zhangwanlin.png

### CODE REVIEW

**Review by Avalionnet — CHANGES_REQUESTED** [review]
Hmm if I remember correctly, we are required to use lowercase for naming our profile image file. Do check it up before merging!

**Review by xz0127 — COMMENTED** [review]
LGTM except the detail that Ming Lim mentioned.

**Comment by ZhangWanlin98** [comment]
> LGTM except the detail that Ming Lim mentioned.

**Comment by WadeForward** [comment]
> Hmm if I remember correctly, we are required to use lowercase for naming our profile image file. Do check it up before merging!

Noticed. Changes have been made 👍

**Review by Avalionnet — APPROVED** [review]
LGTM!!

**Pull request merged**
