### PR TITLE
Add Nric class

### LINKED ISSUE #71: Add IC field for Patients
Create an IC class for patients to add their IC under their profile during registration. An IC field will be added to the Patient class.

### LINKED ISSUE #73: Update UI to display IC field for Patient

### PR DESCRIPTION
**Pull request by Avalionnet**
Added Nric class and relevant methods to validate nric input by nurses.
Modified Nuddle's add and edit commands to support the assignment of 
nric to patients.

This addition helps Nuudle to effectively identify the right patients with their unique
identification number and paves the way for a more efficient search algorithm
to support our appointment system when it is fully implemented.

closes #71

### CODE REVIEW

**Review by JinHao-L — CHANGES_REQUESTED** [review]
Other than the gradle checkstyle violation, LGTM! 👍 

Remember to do the NRIC tests sometime later

**Comment by Avalionnet** [comment]
Thanks @JinHao-L , currently working on the changes!

**Review by xz0127 — COMMENTED** [review]
LGTM! 👍

**Review by JinHao-L — APPROVED** [review]
LGTM 👍

**Comment by Avalionnet** [comment]
Fixed checkstyle, added and modified existing tests to support the addition of Nric.

**Review by YangYue128-helen — COMMENTED** [review]
LGTM!

**Pull request merged**
